### ISSUE TITLE
Support for <style></style> in svelte components

### ISSUE THREAD

**Issue by rraallvv** [pchynoweth/svelte-assets-preprocessor#1]
I'm using this plugin to try to accomplish what `transformToRequire` and `transformAssetUrls`do with the vue-loader plugin in an app that I'm porting to Svelte, but assets used in the `style` section in Svelte components are not preprocessed by this plugin with the default options. Is there a way to accomplish that?

Keep up the good work.

**Comment by pchynoweth** [comment]
Just to be clear.  What you are looking for is something that takes a svetle file like this:

```
<style>
	div {
		height: 100%;
		width: 100%;
		background-size: contain;
		background-repeat: no-repeat;
		background-image: url(https://libreshot.com/wp-content/uploads/2020/03/hills-mist.jpg);
	}
</style>

<div>
</div>
```

And converts the url to a base64 encoding or an import?  That's a bit beyond the scope of this preprocessor.  This preprocessor just converts file paths to imports and replaces the originals with javascript variable so other plugins/loaders can process them.  Svelte doesn't allow you to use javascript variables in the style section so that wouldn't work.  However, if you want base64 encodings, I think you can achieve what you want using the official svelte preprocessor.  It includes a postcss preprocessor.  If you use that with the postcss base64 plugin you might get the results you are looking for.

* Official svelte preprocessor: https://github.com/sveltejs/svelte-preprocess
* Postcss base64 plugin: https://github.com/jelmerdemaat/postcss-base64

**Comment by rraallvv** [comment]
Thanks for the quick reply. Converting the url to base64 would do the job although converting it to an import would work as well, because `url-loader` would take care of making the conversion with webpack.

**Comment by pchynoweth** [comment]
It might not be exactly what you want but you can make `svelte-loader` emit separate css files so they can be processed with regular webpack loaders. For example, this will process the css with `css-loader` and `style-loader`:

```
{
	test: /\.css$/i,
	use: ['style-loader', 'css-loader'],
},
{
	test: /\.(html|svelte)$/,
	exclude: /node_modules/,
	use: {
		loader: 'svelte-loader',
		options: {
			emitCss: true,
		},
	},
},
```

This means the urls are handled by webpack.

**Comment by rraallvv** [comment]
Awesome! Thanks so much. It's very much appreciated.

I'm closing this issue then, since this functionality is beyond the scope of this preprocessor, as you mentioned.
